language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t zafar/mynginx .
#script:
# - docker run -e CI=true zafar/mynginx
#deployment phase
deploy:
 provider: elasticbeanstalk
 region: 
 app: "mynginx"
 env: "Mynginx-env" 
 bucket_name: "mynginx"
 bucket_path: "mynginx"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
